### ISSUE TITLE
Readme not updated to reflect new (?) jsonlog-cli interface

### ISSUE THREAD

**Issue by lschmelzeisen** [borntyping/jsonlog#4]
All in regard to `jsonlog-cli/README.md`:

* The first example given is `jsonlog docs/example.log`. I assume the CLI interface has changed since, because when running this, one only receives:

  ```
  $ jsonlog docs/example.log
  Usage: jsonlog [OPTIONS] COMMAND [ARGS]...
  Try 'jsonlog --help' for help.
  
  Error: No such command 'docs/example.log'.
  ```
* Under the headline **Configuration** three identical example invocations are given, all with different explanations. All of them yield the above error.
* The possibility of a config file and its possible contents/schema are documented nowhere.
* Related: The following invocation currently works and gives a well formated (and colored) traceback.

  ```
  poetry run jsonlog kv docs/example.log 
  timestamp='2019-06-25T17:00:56.929526' name='example' message='debug level log message'
  timestamp='2019-06-25T17:00:56.929690' name='example' message='info level log message'
  timestamp='2019-06-25T17:00:56.929761' name='example' message='warning level log message'
  timestamp='2019-06-25T17:00:56.929819' name='example' message='error level log message'
  timestamp='2019-06-25T17:00:56.929877' name='example' message='error level log message with traceback'

      Traceback (most recent call last):
        File "docs/example.py", line 15, in <module>
          1 / 0
      ZeroDivisionError: division by zero
  
  timestamp='2019-06-25T17:00:56.930077' name='example' message='critical level log message'
  ```
  
  Is there a way to also get the same traceback display when using `jsonlog template`?

**Comment by borntyping** [comment]
- Documentation updated to match new subcommands.
- Documentation updated with better examples.
- Documentation has a section on configuration that describes the config file.
- The `jsonlog template` subcommand has the same multiline keys options as `jsonlog kv` now.

Thanks for highlighting all these issues - it's incredibly useful :)

Changes released in jsonlog 3.2.0 and jsonlog-cli 5.2.0.
